/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Apps: () => import('#controllers/apps_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Distros: () => import('#controllers/distros_controller'),
  Favorites: () => import('#controllers/favorites_controller'),
  Images: () => import('#controllers/images_controller'),
  Pkgs: () => import('#controllers/pkgs_controller'),
  Repos: () => import('#controllers/repos_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Users: () => import('#controllers/users_controller'),
}
