/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Images: () => import('#controllers/images_controller'),
}
