/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSchema extends BaseModel {
  static $columns = ['appstreamContent', 'appstreamId', 'appstreamUrl', 'createdAt', 'desktopContent', 'desktopUrl', 'homepage', 'iconId', 'id', 'license', 'name', 'summary', 'updatedAt', 'version'] as const
  $columns = AppSchema.$columns
  @column()
  declare appstreamContent: string | null
  @column()
  declare appstreamId: string | null
  @column()
  declare appstreamUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare desktopContent: string | null
  @column()
  declare desktopUrl: string | null
  @column()
  declare homepage: string | null
  @column()
  declare iconId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare license: string | null
  @column({ prepare: (value)=>value ? JSON.stringify(value) : value, consume: (value)=>typeof value === 'string' ? JSON.parse(value) : value })
  declare name: Record<string, string>
  @column({ prepare: (value)=>value ? JSON.stringify(value) : value, consume: (value)=>typeof value === 'string' ? JSON.parse(value) : value })
  declare summary: Record<string, string>
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class AppCategorySchema extends BaseModel {
  static $columns = ['appId', 'categoryId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AppCategorySchema.$columns
  @column()
  declare appId: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'parentId', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column({ prepare: (value)=>value ? JSON.stringify(value) : value, consume: (value)=>typeof value === 'string' ? JSON.parse(value) : value })
  declare name: Record<string, string>
  @column()
  declare parentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DistroSchema extends BaseModel {
  static $columns = ['arch', 'createdAt', 'eolDate', 'id', 'name', 'pkgType', 'releaseDate', 'updatedAt', 'version'] as const
  $columns = DistroSchema.$columns
  @column({ prepare: (value)=>value ? JSON.stringify(value) : value, consume: (value)=>typeof value === 'string' ? JSON.parse(value) : value })
  declare arch: string[]
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare eolDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare pkgType: string | null
  @column.date()
  declare releaseDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class FavoriteSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = FavoriteSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ImageSchema extends BaseModel {
  static $columns = ['createdAt', 'height', 'id', 'mimeType', 'path', 'size', 'updatedAt', 'userId', 'width'] as const
  $columns = ImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare path: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare width: number
}

export class PkgSchema extends BaseModel {
  static $columns = ['appId', 'arch', 'checksum', 'checksumType', 'createdAt', 'description', 'downloadUrl', 'id', 'installCommand', 'license', 'name', 'path', 'release', 'repoId', 'size', 'summary', 'type', 'updatedAt', 'userId', 'version'] as const
  $columns = PkgSchema.$columns
  @column()
  declare appId: number | null
  @column()
  declare arch: string | null
  @column()
  declare checksum: string | null
  @column()
  declare checksumType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare downloadUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installCommand: string | null
  @column()
  declare license: string | null
  @column()
  declare name: string
  @column()
  declare path: string | null
  @column()
  declare release: string | null
  @column()
  declare repoId: number | null
  @column()
  declare size: number | null
  @column()
  declare summary: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare version: string | null
}

export class RepoSchema extends BaseModel {
  static $columns = ['baseUrl', 'configContent', 'configUrl', 'createdAt', 'distroId', 'id', 'installScript', 'lastSyncedAt', 'name', 'source', 'syncIntervalDays', 'type', 'updatedAt'] as const
  $columns = RepoSchema.$columns
  @column()
  declare baseUrl: string
  @column()
  declare configContent: string | null
  @column()
  declare configUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distroId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installScript: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare source: string
  @column()
  declare syncIntervalDays: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['appId', 'comment', 'createdAt', 'id', 'rating', 'updatedAt', 'userId'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare appId: number
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
