/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AppTransformer from '#transformers/app_transformer'
import type ImageTransformer from '#transformers/image_transformer'
import type PkgTransformer from '#transformers/pkg_transformer'
import type RepoTransformer from '#transformers/repo_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type App = InferData<AppTransformer>
  export namespace App {
    export type Variants = InferVariants<AppTransformer>
  }
  export type Image = InferData<ImageTransformer>
  export namespace Image {
    export type Variants = InferVariants<ImageTransformer>
  }
  export type Pkg = InferData<PkgTransformer>
  export namespace Pkg {
    export type Variants = InferVariants<PkgTransformer>
  }
  export type Repo = InferData<RepoTransformer>
  export namespace Repo {
    export type Variants = InferVariants<RepoTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
